config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "meetings#index"
  resources :rooms
  resources :meetings, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  default_scope { order(scheduled_at: :asc) }
  belongs_to :room
  belongs_to :user
  validates :title, :day, :scheduled_at, presence: true
  validates :title, uniqueness: true, if: :uniqueness_by_user?
  validates_associated :room
  validates_associated :user

  attr_accessor :date_start, :date_end

  def start_time
    day
  end

  protected

    def identical_meeting
      Room.joins(:meetings).where("
        rooms.title = ? AND
        meetings.user_id != ? AND
        meetings.day = ? AND
        meetings.scheduled_at = ?",
          room.title,
          user.id,
          day,
          scheduled_at
      ).exists?
    end

    def uniqueness_by_user?
      if room.present? && user.present? && title.present? && day.present? && scheduled_at.present? && !identical_meeting
        false
      else
        true
      end
    end
end

app/models/room.rb
class Room < ApplicationRecord
  default_scope { order(created_at: :desc) }
  has_many :meetings, autosave: true, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :meetings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  include CableReady::Broadcaster

  def index
    date_to_start = !params[:start_date].blank? ? params[:start_date].to_date.beginning_of_month : Date.today.beginning_of_month
    date_to_end = date_to_start.end_of_month
    @meetings = Meeting.where("day between ? and ?", date_to_start, date_to_end).all
    @meeting = Meeting.new
  end

  def create
    date_start = params[:date_start]
    date_start = Date.today.change(
      year: date_start["(1i)"].to_i,
      month: date_start["(2i)"].to_i,
      day: date_start["(3i)"].to_i
    )

    date_end = params[:date_end]
    date_end = Date.today.change(
      year: date_end["(1i)"].to_i,
      month: date_end["(2i)"].to_i,
      day: date_end["(3i)"].to_i
    )

    days = (date_end - date_start).to_i
    if days == 0
      dates = [date_start]
    else
      dates = (0..days).collect do |day|
        date_start + day.day
      end
    end

    meeting = current_user.meetings.build(meeting_params)
    meeting.user_id = current_user.id
    dates.each do |date|
      new_meeting = current_user.meetings.build(
        user_id: meeting.user_id,
        room_id: meeting.room_id,
        title: meeting.title,
        scheduled_at: meeting.scheduled_at,
        day: date
      )
      new_meeting.save
    end

    meetings = Meeting.where("day between ? and ?", dates.first.beginning_of_month, dates.first.end_of_month).all

    cable_ready["meetings"].inner_html(
      selector: "#calendar",
      html: render_to_string(partial: "calendar", locals: {global_meetings: meetings})
    )
    cable_ready.broadcast

    redirect_to meetings_path(start_date: dates.first.beginning_of_month)
  end

  private
    def meeting_params
      params.require(:meeting).permit(:title, :room_id, :scheduled_at)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  include CableReady::Broadcaster
  before_action :set_room, :only_if_exists, only: [:edit, :update, :destroy]
  before_action :set_rooms, only: [:edit,:index]

  def index
    @room = Room.new
  end

  def create
    Room.create(room_params)
    dispatch_update_room_list
    redirect_to rooms_path
  end

  def edit
    render action: :index
  end

def update
  room = Room.find(params[:id])
  dispatch_update_room_list if room.update_attributes(room_params)

  redirect_to rooms_path
end


  def destroy
    @room.destroy
    cable_ready["rooms"].remove(
      selector: "#room-#{@room.id}"
    )
    cable_ready.broadcast
    redirect_to rooms_path
  end

  private
    def set_rooms
      @rooms = Room.all
    end

    def set_room
      @room = Room.find(params[:id])
    end

    def only_if_exists
      redirect_to rooms_path unless @room.present?
    end

    def room_params
      params.require(:room).permit(:title)
    end

    def dispatch_update_room_list
      cable_ready["rooms"].insert_adjacent_html(
        selector: "#rooms",
        position: "afterbegin",
        html: render_to_string(partial: "room", collection: Room.all)
      )
      cable_ready.broadcast
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def short_meeting_title(meeting)
    "#{l(meeting.scheduled_at, format: :short)} - #{meeting.title.truncate(14)}"
  end

  def long_meeting_title(meeting)
    "Room: #{meeting.room.title} created by #{meeting.user.email} at #{l(meeting.scheduled_at, format: :short)} - #{meeting.title.truncate(14)}"
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Simple Meetings</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
  <div class="container h-100">
    <div class="row mt-4 justify-content-center align-items-center">
      <div class="col-12">
        <h2 id="application_title">Simple Meetings <small><%="Hello #{current_user.email}" if user_signed_in?%></small></h2>
        <div class="btn-group mt-2" role="group" aria-label="Application Actions">
          <%= link_to "Dashboard/Create Meeting", root_path, class:"btn btn-primary" %>
          <%= link_to "Create Room", rooms_path, class:"btn btn-secondary" %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"btn btn-secondary" if user_signed_in? %>
        </div>
        <hr />
      </div>
    </div>
    <%= yield %>
  </div>
</body>

</html>

app/views/meetings/_calendar.html.erb
<%= month_calendar events: global_meetings do |date, meetings| %>
  <%= date %><br />
  <% meetings.each do |meeting| %>
    <a class="badge badge-success" href="javascript:void(0)" title="<%= long_meeting_title(meeting) %>">
      <%= short_meeting_title(meeting) %>
    </a>
  <% end %>
<% end %>

app/views/meetings/_form.html.erb
<%= form_with(model: @meeting, local: true, url: {controller: :meetings, action: :create}) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.label :room_id, class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.select :room_id, Room.all.collect {|r| [ r.title, r.id ] }, { prompt: 'Select a Room' }, { style: 'width: 100%', class: 'form-control', required: true } %>
      </div>
    </div>

    <div class="col-md-6">
      <%= f.label :title, class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.text_field :title, class: 'form-control', placeholder: 'title...', required: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= label_tag :date_start, "Date start", class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= date_select :date_start, "", {}, { class: 'form-control', style: 'width: auto; display: inline' } %>
      </div>
    </div>
    <div class="col-md-6">
      <%= label_tag :date_end, "Date end", class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= date_select :date_end, "", {}, { class: 'form-control', style: 'width: auto; display: inline' } %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= f.label :scheduled_at, class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.time_select :scheduled_at, { start_hour: 8, end_hour: 17, use_month_numbers: true }, { class: 'form-control d-inline', style: 'width: auto' } %>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-md-12">
      <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary btn-save-meeting" %>
      </div>
    </div>
  </div>
<% end %>

app/views/meetings/index.html.erb
<h5>Dashboard for Meetings</h5>

<%= render 'form' %>
<div id="calendar">
  <%= render partial: "calendar", locals: {global_meetings: @meetings} %>
</div>

app/views/rooms/_form.html.erb
<%= form_with model: room, local: true, html: {class: "my-4"} do |form| %>
  <div class="form-group">
    <%= form.text_field :title, placeholder: "Enter with the title of room", class: "form-control", required: true %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div class="card mb-2 bg-light" id="room-<%= room.id %>">
  <div class="card-body">
    <h4 class="card-title text-muted">
      <%= room.title %>
      <small>-- <%=time_ago_in_words room.created_at %>: <%= room.meetings.count %> meetings</small>
    </h4>
    <p class="card-text lead">
      <!-- <button data-reflex="click->Rooms#edit" data-room-id="<%= room.id %>" class="btn btn-secondary">Edit</button> -->
      <%= link_to 'Edit', edit_room_path(room), class: "btn btn-secondary" %>
      <%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    </p>
  </div>
</div>

app/views/rooms/index.html.erb
<h5>Dashboard for Rooms</h5>

<%= render partial: 'form', locals: { room: @room } %>
<div id="rooms">
  <%= render partial: "room", collection: @rooms %>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, class: 'btn btn-primary' %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view, class: 'btn btn-primary' %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<hr />
<div class="simple-calendar">
  <h5>Calendar to month: <%= start_date.all_month %></h5>
  <div class="calendar-heading mb-2">
    <%= link_to t('simple_calendar.previous', default: 'Previous month'), calendar.url_for_previous_view, class: 'btn btn-secondary' %>
    <%= link_to t('simple_calendar.next', default: 'Next month'), calendar.url_for_next_view, class: 'btn btn-secondary' %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>